version: '3'

services:
  web:
    restart: always
    build: .
    networks:
      - default
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:9000"
    volumes:
      - .:/code
    ports:
      - "9000:9000"
